# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          "/stash/pages/WEBSTYLE/jcu-web-framework/gh-pages/browse"
url:              http://getbootstrap.com
encoding:         UTF-8
timezone:         Australia/Brisbane
exclude:          [assets/scss/]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom vars
current_version:  4.0.0-alpha
repo:             https://git.jcu.edu.au/stash/projects/WEBSTYLE/repos/jcu-web-framework
sass_repo:        https://github.com/twbs/bootstrap-sass
slack:            ''

download:
  source:         https://github.com/twbs/bootstrap/archive/v4.0.0-alpha.zip
  dist:           https://github.com/twbs/bootstrap/releases/download/v4.0.0-alpha/bootstrap-4.0.0-alpha-dist.zip

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com
themes:           http://themes.getbootstrap.com

cdn:
  css:            https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css
  js:             https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js
  jquery:         https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js
